version: '3.8'

services:
  app:
    container_name: node-server-container
    restart: always
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app

  mongodb:
    container_name: mongo-database
    image: mongo
    ports:
      - '27017:27017'
    depends_on:
      - app
